#'
#' Function to save results generated by ropensci
#' @param x data variable
#' @param type=NULL csv, JSON for data sources. png, tiff,eps for figures
rosave<- function(x,type=NULL)
{
	stop('saving in development')
}

#'
#' Function to plot standard outputs from ropensci
#' @param obj data object to be plotted
roplot<-function(obj)
{
	stop('Plotting in development')
}

#'
#' Generic method to summarize ropensci objects
#' @param obj result set
summary<-function(obj)
{
	stop('Summary in development')
}

setGeneric("rosave")
setGeneric("roplot")
setGeneric("summary")